import { useMemo, useState } from 'react';
import AdvisorIcon from './AdvisorIcon';
import { castingClasses, categoryForSpell, recommendHotbars, spellCatalog, spellCategoryName, type SpellCategory } from '../lib/spell-hotbar';
import type { AdvisorInput, RulePack } from '../lib/build-advisor';
import '../app/spell-hotbar.css';

const categoryIcons: Record<SpellCategory, string> = { damage: '🔥', dot: '☠️', heal: '✨', cure: '🧪', control: '🔮', debuff: '⬇️', buff: '🛡️', pet: '🐾', travel: '🌀', stealth: '🌑', utility: '🧭' };
const categories = Object.keys(categoryIcons) as SpellCategory[];
export default function SpellHotbarPlanner({ input, pack }: { input: AdvisorInput; pack: RulePack }) {
  const [spellSlots, setSpellSlots] = useState(14), [meleeSlots, setMeleeSlots] = useState(8), [query, setQuery] = useState(''), [classFilter, setClassFilter] = useState(''), [categoryFilter, setCategoryFilter] = useState<'' | SpellCategory>(''), [availableOnly, setAvailableOnly] = useState(true), [page, setPage] = useState(0);
  const plan = useMemo(() => recommendHotbars(input, pack, spellSlots, meleeSlots), [input, pack, spellSlots, meleeSlots]);
  const level = input.level ?? 65, trio = [input.primary, input.secondary, input.tertiary].filter(Boolean);
  const results = useMemo(() => spellCatalog.spells.filter(spell => (!query.trim() || spell.name.toLowerCase().includes(query.trim().toLowerCase())) && (!classFilter || spell.classes.some(c => c.id === classFilter)) && (!categoryFilter || categoryForSpell(spell) === categoryFilter) && (!availableOnly || spell.classes.some(c => trio.includes(c.id) && c.level <= level))), [query, classFilter, categoryFilter, availableOnly, trio.join('|'), level]);
  const pageRows = results.slice(page * 30, page * 30 + 30), pages = Math.max(1, Math.ceil(results.length / 30));
  function changeFilters(fn: () => void) { fn(); setPage(0); }
  return <section className="spell-planner" aria-label="Spell and hotbar planner">
    <header><AdvisorIcon code="book" /><div><h3>Spell &amp; Hotbar Planner</h3><p>Use your selected trio and goals to arrange a practical spell bar and action bar.</p></div></header>
    <div className="spell-source"><strong>Offline catalog:</strong> {spellCatalog.spells.length} EQL spell records · reviewed {spellCatalog.reviewedOn} · <a href={spellCatalog.source.url} target="_blank" rel="noreferrer">{spellCatalog.source.title}</a><small>{spellCatalog.provenance.label} · {spellCatalog.source.note}</small></div>
    <div className="spell-slot-controls"><label>Spell-bar slots<select value={spellSlots} onChange={e => setSpellSlots(Number(e.target.value))}>{[8, 10, 12, 14].map(value => <option key={value} value={value}>{value} slots</option>)}</select></label><label>Action-bar slots<select value={meleeSlots} onChange={e => setMeleeSlots(Number(e.target.value))}>{[6, 8, 10, 12].map(value => <option key={value} value={value}>{value} slots</option>)}</select></label></div>
    <div className="spell-notices">{plan.notices.map(note => <p key={note}>{note}</p>)}</div>
    <section className="hotbar-section"><h4>✨ Suggested live spell bar</h4><p>Slots are ordered by what the current goal needs most. Put spells you cannot use yet in the preparation set instead.</p><div className="hotbar-grid">{plan.spellBar.map((spell, index) => <article key={spell.name} className={`hotbar-slot spell-${spell.category}`}><b>{index + 1}</b><span>{categoryIcons[spell.category]}</span><div><strong>{spell.name}</strong><small>{spell.classId} · Level {spell.availableAt} · {spellCategoryName(spell.category)}</small></div><p>{spell.reason}</p></article>)}{Array.from({ length: Math.max(0, spellSlots - plan.spellBar.length) }, (_, index) => <div className="hotbar-empty" key={`empty-${index}`}>Open slot</div>)}</div></section>
    <section className="hotbar-section"><h4>🛡️ Preparation, travel &amp; buff set</h4><p>These are useful before a pull or while traveling. They are kept separate to reduce combat-bar clutter.</p><div className="spell-chip-list">{plan.preparation.length ? plan.preparation.map(spell => <span key={spell.name}>{categoryIcons[spell.category]} <strong>{spell.name}</strong><small>{spell.classId} · L{spell.availableAt}</small></span>) : <p>No preparation spells match the current trio and level.</p>}</div></section>
    <section className="hotbar-section"><h4>🗡️ Suggested actions / melee hotbar</h4><p>Use the highest priority learned actions first. These are starter positions, not a statement that every action is learned at your level.</p><div className="hotbar-grid hotbar-actions">{plan.meleeBar.length ? plan.meleeBar.map((ability, index) => <article key={`${ability.class}-${ability.name}`} className={`hotbar-slot action-${ability.kind}`}><b>{index + 1}</b><span>{ability.kind === 'heal' ? '✨' : ability.kind === 'control' ? '🎯' : ability.kind === 'defense' ? '🛡️' : ability.kind === 'utility' ? '🧭' : '⚔️'}</span><div><strong>{ability.name}</strong><small>{ability.class} · {ability.kind}</small></div><p>{ability.reason}</p></article>) : <p className="ba-note">This trio has no melee action records in the local starter data. Use your learned EQL Abilities window to fill these slots.</p>}</div></section>
    <details className="spell-catalog"><summary>Browse the full local spell catalog ({spellCatalog.spells.length} records)</summary><p>Search stays on this device. The catalog shows only factual spell-table fields; it does not guess values from combat logs.</p><div className="spell-filters"><label>Search spell<input value={query} onChange={e => changeFilters(() => setQuery(e.target.value))} placeholder="Spell name" /></label><label>Class<select value={classFilter} onChange={e => changeFilters(() => setClassFilter(e.target.value))}><option value="">All listed classes</option>{castingClasses().map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label>Type<select value={categoryFilter} onChange={e => changeFilters(() => setCategoryFilter(e.target.value as '' | SpellCategory))}><option value="">All types</option>{categories.map(category => <option key={category} value={category}>{categoryIcons[category]} {spellCategoryName(category)}</option>)}</select></label><label className="spell-available"><input type="checkbox" checked={availableOnly} onChange={e => changeFilters(() => setAvailableOnly(e.target.checked))} /> Available to this trio at level {level}</label></div><p>{results.length} matching record{results.length === 1 ? '' : 's'} · page {page + 1} of {pages}</p><div className="ba-table-wrap"><table><thead><tr><th>Spell</th><th>Class / level</th><th>Use</th><th>Mana</th><th>Cast / recast</th><th>Duration / target</th></tr></thead><tbody>{pageRows.map((spell, index) => <tr key={`${spell.name}-${spell.level}-${index}`}><th scope="row">{categoryIcons[categoryForSpell(spell)]} {spell.name}</th><td>{spell.classes.map(c => `${c.id} L${c.level}`).join(', ')}</td><td>{spellCategoryName(categoryForSpell(spell))}</td><td>{spell.mana ?? '—'}</td><td>{spell.cast ?? '—'}s / {spell.recast ?? '—'}s</td><td>{spell.duration || '—'} · {spell.target || '—'}</td></tr>)}</tbody></table></div><div className="spell-pages"><button type="button" disabled={page === 0} onClick={() => setPage(value => value - 1)}>Previous</button><button type="button" disabled={page + 1 >= pages} onClick={() => setPage(value => value + 1)}>Next</button></div></details>
  </section>;
}
